apiVersion: apps/v1
kind: Deployment
metadata:
  name: ARTIFACT_ID-deployment
spec:
  selector:
    matchLabels:
      app: ARTIFACT_ID
  template:
    metadata:
      labels:
        app: ARTIFACT_ID
    spec:
      containers:
      - name: ARTIFACT_ID
        readinessProbe:
          periodSeconds: 10
        imagePullPolicy: Always
        image: gcr.io/google-containers/ARTIFACT_ID
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080



