apiVersion: apps/v1
kind: Deployment
metadata:
  name: app # Used for kustomize matching
spec:
  template:
    spec:
      containers:
        - name: app # Used for kustomize matching
          imagePullPolicy: IfNotPresent  # for use with minikube, not to try and download from remote registry first.