# Generated on Fri Aug 09 09:51:04 EDT 2019
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdemo
spec:
  selector:
    matchLabels:
      app: webdemo
  replicas: 1
  template:
    metadata:
      labels:
        app: webdemo
    spec:
      containers:
        - name: webdemo
          image: docker.io/markpollack/testing:0.0.3
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080