---
conditional:
  onDependency: mysql-connector-java
actions:
  to: kubernetes/overlays/local-services/mysql/mysql-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql