apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Hello, I am local!
  labels:
    app.kubernetes.io/name: webdemo
    variant: local
  name: webdemo-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: webdemo
    variant: local
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    note: Hello, I am local!
  labels:
    app.kubernetes.io/name: webdemo
    variant: local
  name: webdemo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webdemo
      variant: local
  template:
    metadata:
      annotations:
        note: Hello, I am local!
      labels:
        app.kubernetes.io/name: webdemo
        variant: local
    spec:
      containers:
      - image: lift/webdemo:latest
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 8080
