apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Hello, I am dev!
  labels:
    app.kubernetes.io/name: webdemo
    author: markp
    variant: dev
  name: webdemo-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: webdemo
    author: markp
    variant: dev
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    note: Hello, I am dev!
  labels:
    app.kubernetes.io/name: webdemo
    author: markp
    variant: dev
  name: webdemo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: webdemo
      author: markp
      variant: dev
  template:
    metadata:
      annotations:
        note: Hello, I am dev!
      labels:
        app.kubernetes.io/name: webdemo
        author: markp
        variant: dev
    spec:
      containers:
      - image: docker.io/markpollack/testing:latest
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8080
