# Generated on Fri Aug 09 09:51:04 EDT 2019
kind: Service
apiVersion: v1
metadata:
  name: webdemo
  labels:
    app: webdemo
spec:
  type: NodePort
  ports:
    - port: 8080
      name: webdemo
  selector:
    app: webdemo